:repo: database
:project: Shabad OS (Database)
:idprefix:
:hide-uri-scheme:
:numbered:
:max-width: 900px
:icons: font
:toc: macro
:toclevels: 4
ifdef::env-github,env-browser[:outfilesuffix: .asciidoc]
ifdef::env-github[]
:note-caption: :information_source:
:tip-caption: :bulb:
:important-caption: :fire:
:caution-caption: :warning:
:warning-caption: :no_entry:
endif::[]

[discrete]
# Contributing to {project}

Thank you for your interest in participating!

There are many ways for people to contribute, beyond writing code or programming, by: proofreading, reviewing sources, and creating tickets. All of which can be learned in our https://tutorials.shabados.com/tutorials/1.0.0/database-viewer/proofreading.html[proofreading] tutorial. See our readme for other ways to link:README.adoc#Contributing[Contribute] or give link:README.adoc#Feedback[Feedback].

This document is for developers or programmers that wish to write code and directly contribute to the source code of {project}.

toc::[id="toc"]

## Getting Started

If you wish to better understand how the `{repo}` repo works or want to debug an issue: get the source, build it, and run it locally.

### Prerequisites

In order to download necessary tools, clone the repository, and install dependencies, you'll need network access. To view the database you'll need a database viewer (e.g. https://dbeaver.io/[DBeaver]).

* https://git-scm.com/[Git]
* Source code of `{repo}` repo. We recommend forking the repo on GitHub and cloning that to your local machine.
* https://nodejs.org/en/[Node.js]

NOTE: If you need to manage multiple Node.js versions, use a node version manager to install https://docs.npmjs.com/downloading-and-installing-node-js-and-npm[Node.js].

### Build

Run `npm i` in the root directory. Build an sqlite file by entering `npm run build-sqlite`.

### Run

Usage: 
----
npm run <command>
----

The commands are:
----
build-sqlite  Generate an sqlite db in the build folder
build-mysql   Generate a mySQL db in the build folder

build-json    Generate a json file of build/database.sqlite
import        Import an sqlite db into build/database.sqlite
generate-id   Generate unique ID for shabad or line

benchmark
release 
precommit
serve-docs
----

NOTE: Mass changes can be made to the repo by building an sqlite file, editing it, then building the json from it to commit upstream. Mass changes are usually reserved for cases like renaming the transliteration of a name. These changes will not be accepted from outside collaborators and is reserved for maintainers, admins, or owners of the Shabad OS project. 

NOTE: It's possible to import other sqlite files. Run `npm run import -- --help` to see all options. The importer will generate placeholder Sources, Translation Sources, and fill in -1 for Shabad sections and Writer IDs. These must be corrected in `build/database.sqlite`. Then you will need to follow the note above to commit changes. Importing is reserved for maintainers, admins, or owners of the Shabad OS project.

Example import command:
----
npm run import -- nandlal.sqlite nandlal -o ID -s ShabadID -2 ShabadID -S SourceID -t English -t Punjabi -p PageNo -l LineNo -g Gurmukhi
----

### Docker

In addition to the above comamnds, you can run a Shabad OS MariaDB using Docker (username: `shabados`, database name: `shabados`):
----
docker run -p 3306:3306 shabados/database
----

If you'd like to build the image yourself, run:
----
`docker build -f docker/mariadb/Dockerfile -t shabados/database .`.
----

## File/Folder Structure

### Schema

The schema can be modified in the `migrations/schema.js` file. 

JSON files for `Raags`, `Sources`, `Writers`, and `Line_Types` can be found in the `data` folder. Changing a value here will be reflected everywhere else. The `(array index) + 1` represents the id used for each relation in other tables.

Lines of JSON files are split by page or other sensible method via `./data/source/number.json`.

Bani compilations can be added to the `bani.json`. To define the lines it contains, each bani should contain a list of objects with `start_line` and `end_line`, referring to the files in `sources`.

### Data Folder

Binary files are difficult to track in git. Therefore the JSON files in the data folder is used as the source of truth for the Shabad OS Database.

* Source folders - JSON files contain the id, gurmukhi, pronunciation, and translations of each line of parent folder's source
* JSON files - these files range from compiling banis, separating sections and sub-sections, to naming languages, translations, and writers

## Workflow

The general workflow of development is to choose an issue to work on, create a feature branch off `dev` branch, and submit a pull request. This model is shared across all repos in the Shabad OS organization.

IMPORTANT: Please see the shared docs for Workflow (Issue Tracking, Branching, and Pull Requests) in the link:https://github.com/ShabadOS/.github/wiki/How-to-Contribute#workflow[How To Contribute wiki article].

## Coding Guidelines

Our coding guidelines are also (mostly) shared across all repos in the Shabad OS organization. Aside from scope definitions (which are repo specific), the rest should be referenced in the wiki article.

IMPORTANT: Please see the shared docs for Coding Guidelines (Names, Comments, Style, Linting, and Commit Messages) in the link:https://github.com/ShabadOS/.github/wiki/How-to-Contribute#coding-guidelines[How to Contribute wiki article].

### Scope (Part of link:https://github.com/ShabadOS/.github/wiki/How-to-Contribute#commit-messages[Commit Messages])

The scope should be the name of the npm package affected (as perceived by the person reading the changelog generated from commit messages). There are currently no scopes in `{repo}`.

There are currently a few exceptions to the "use package name" rule:

- *none/empty string*: useful for `style`, `test`, and `refactor` changes that are done across all packages (e.g. style: add missing semicolons) and for `docs` changes that are not related to a specific package (e.g. docs: fix typo in tutorial).

## Thank you!

Your contributions to open source, large or small, make great projects like this possible. Thank you for taking the time to participate in this project.