[name]
en = "Sundar Gutka Damdami Taksal"
pa = "ਸੁੰਦਰ ਗੁਟਕਾ ਦਮਦਮੀ ਟਕਸਾਲ"

[reference]
title = "ਦਮਦਮੀ ਟਕਸਾਲ ਵਾਲਾ ਸੁੰਦਰ ਗੁਟਕਾ"
url = "https://archive.org/details/sundar-gutka-damdami-taksal-complete_202308/mode/2up"

[[reference.authors]]
first = "Darshan Singh"
last = "Mallewal"
role = "Editor"

[reference.publisher]
name = "Damdami Taksal"
