[name]
en = "Sundar Gutka Damdami Taksal"
pa = "ਸੁੰਦਰ ਗੁਟਕਾ ਦਮਦਮੀ ਟਕਸਾਲ"

[reference]
title = "Sundar Gutka Damdami Taksal"
url = "https://archive.org/details/sundar-gutka-damdami-taksal-complete_202308/mode/2up"

[[reference.authors]]
role = "Editor"
first = "Darshan Singh"
last = "Mallewal"
prefix = "Bhai"

[reference.publisher]
name = "Damdami Taksal"
