[[content]]
asset = "DGDG"
type = "primary"
data = "ਸੰਬਤ ਸਤ੍ਰਹ ਸਹਸ ਭਣਿਜੈ ॥"
page = 1388

[[content]]
asset = "RSJD"
type = "translation"
language = "pa"
data = "(ਪਹਿਲਾਂ) ਸਤਾਰਾਂ ਸੌ ਸੰਮਤ ਕਹੋ"

[[content]]
asset = "DDTK"
type = "primary"
data = "ਸੰਬਤ ਸੱਤ੍ਰਹ; ਸਹਸ ਭਣਿੱਜੈ ॥"
page = 1388